/*
 * This file was generated by the Gradle 'init' task.
 */

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files(rootDir.resolve("libs.versions.toml")))
        }
    }
}

rootProject.name = "simple_http_server"
include("server")
include("framework")
include("demo")
include("reactive")
include("recurring")
include("contract")
